project:
  type: website
  title: "FICM Intensivists in Training"
  # For GitHub Pages compatibility
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "FICM Intensivists in Training"
  navbar:
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "The Good, The Bad and The Necessary"
        href: good_bad_nec.qmd
      - text: "A look under the hood"
        href: under_the_hood.qmd
      - text: "From vibes to context engineering"
        href: vibes_to_engineer.qmd
format:
  html:
    theme: [default, brand]
    css: style/style.css
  revealjs:
    theme: [default, brand, style/brc-revealjs-overrides.scss]
    brand-mode: dark
    css: style/style.css
    template-partials:
      - style/title-slide.html
    # multiplex:
    #   url: "https://multiplex.up.railway.app/"
