project:
  title: A Project Title
  output-dir: docs
format:
  html:
    theme: [default, brand]
    css: style/style.css
  revealjs:
    theme: [default, brand, style/brc-revealjs-overrides.scss]
    brand-mode: dark
    css: style/style.css
    template-partials:
      - style/title-slide.html
    multiplex:
      url: "https://multiplex.up.railway.app/"
